spring:
  profiles:
    active: local

  application:
    name: fra

  flyway:
    enabled: false

  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl # ??? ??? ??
      ddl-auto: validate
    properties:
      hibernate:
        query.in_clause_parameter_padding: true
        default_batch_fetch_size: 50
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
        format_sql: false
        show_sql: false
        use_sql_comments: false
        jmx.enabled: true
    open-in-view: false